xap/xap

xap-core/xap-datagrid/src/main/java/com/j_spaces/core/transaction/TransactionHandler.java, xap-core/xap-openspaces/src/main/java/org/openspaces/events/AbstractEventListenerContainer.java, xap-core/xap-openspaces/src/main/java/org/openspaces/events/polling/SimplePollingEventListenerContainer.java
GS-13284 clone snapshot + add roll back handle exception
=> Gs 13284 clone snapshot

xap-core/xap-openspaces/pom.xml, xap-dist/src/main/assembly/xap-openspaces.xml
move commons-collection to lib/optional/jpa 
upgrade to 3.2.2
=> Xap move commons collections

xap-core/xap-datagrid/src/main/java/com/j_spaces/core/cache/blobStore/offheap/OffHeapMemoryPool.java, xap-core/xap-datagrid/src/test/java/com/j_spaces/core/cache/blobStore/offheap/BlobStoreOffHeapInfoMock.java, xap-core/xap-datagrid/src/test/java/com/j_spaces/core/cache/blobStore/offheap/OffHeapMemoryPoolTest.java
=> Off heap memory pool unit test

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/cluster/node/impl/config/DynamicSourceGroupConfigHolder.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/SpaceEngine.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/executors/SpaceRegisterReplicationNotificationExecutor.java
=> GS-13922 - Reduced redolog contention for dynamic channel registration

xap-core/xap-common/src/main/java/org/jini/rio/boot/ServiceClassLoader.java
=> GS-14054 Added auto-detection for slf4j class loader misconfiguration

xap-core/xap-datagrid/src/main/java/com/gigaspaces/attribute_store/AttributeStore.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/attribute_store/PropertiesFileAttributeStore.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/attribute_store/SharedLock.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/attribute_store/SharedLockProvider.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/attribute_store/SimulatedSharedLockProvider.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/attribute_store/TransientAttributeStore.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/ZookeeperChunksMapHandler.java, xap-core/xap-datagrid/src/test/java/com/gigaspaces/attribute_store/SimulatedSharedLockProviderTest.java
=> GS-14128 created pu.lock abstraction

xap-core/xap-datagrid/src/main/java/com/gigaspaces/cluster/DynamicPartitionInfo.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/cluster/PartitionRoutingInfo.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/datasource/SpaceDataSource.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/cluster/DynamicPartitionInfoImpl.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/cluster/PartitionRoutingInfoImpl.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/SpaceEngine.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/executors/SpaceDataSourceLoadExecutor.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/space/requests/DataSourceLoadSpaceRequestInfo.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/sync/SynchronizationStorageAdapter.java, xap-core/xap-openspaces/src/main/java/org/openspaces/core/cluster/ClusterInfo.java, xap-core/xap-openspaces/src/main/java/org/openspaces/core/cluster/ClusterInfoBuilder.java, xap-core/xap-openspaces/src/main/java/org/openspaces/core/cluster/internal/ClusterInfoImpl.java, xap-extensions/xap-mongodb/src/main/java/com/gigaspaces/persistency/MongoSpaceDataSource.java
Added abstraction to encapsulate info required to optimize initial load process for specific partition
=> GS-14102 added PartitionRoutingInfo for initial load

xap-core/xap-datagrid/src/main/java/com/j_spaces/jdbc/SelectQuery.java, xap-core/xap-datagrid/src/main/java/com/j_spaces/jdbc/builder/QueryTemplatePacket.java
set newly added fields in .clone method
=> GS-14313 serialize two more relevant fields for collocated join

xap-core/xap-common/src/main/java/com/gigaspaces/start/SystemLocations.java
- removed SystemLocations.userProductHome()
- removed unused PersistentServiceStatementManager
- removed checkAccess for unused dirs (native, logs, records)
=> GS-14531 store rio user files under work/rio

xap-extensions/xap-aggregator-node/src/main/java/com/gigaspaces/sql/aggregatornode/netty/query/QueryPortal.java, xap-extensions/xap-aggregator-node/src/main/java/com/gigaspaces/sql/aggregatornode/netty/query/QueryProviderImpl.java, xap-extensions/xap-aggregator-node/src/main/java/com/gigaspaces/sql/aggregatornode/netty/query/Session.java, xap-extensions/xap-aggregator-node/src/main/java/com/gigaspaces/sql/aggregatornode/netty/server/MessageProcessor.java, xap-extensions/xap-aggregator-node/src/main/java/com/gigaspaces/sql/aggregatornode/netty/utils/DateTimeUtils.java, xap-extensions/xap-aggregator-node/src/main/java/com/gigaspaces/sql/aggregatornode/netty/utils/TypeDate.java, xap-extensions/xap-aggregator-node/src/main/java/com/gigaspaces/sql/aggregatornode/netty/utils/TypeTamestampTZ.java, xap-extensions/xap-aggregator-node/src/main/java/com/gigaspaces/sql/aggregatornode/netty/utils/TypeTime.java, xap-extensions/xap-aggregator-node/src/main/java/com/gigaspaces/sql/aggregatornode/netty/utils/TypeTimeTZ.java, xap-extensions/xap-aggregator-node/src/main/java/com/gigaspaces/sql/aggregatornode/netty/utils/TypeTimestamp.java, xap-extensions/xap-aggregator-node/src/main/java/com/gigaspaces/sql/aggregatornode/netty/utils/TypeUtils.java, xap-extensions/xap-aggregator-node/src/test/java/com/gigaspaces/sql/aggregatornode/netty/server/ServerBeanTest.java
Text serialization is implemented for all expected date time types.
=> PG date time serialization

xap-core/xap-datagrid/config/metrics/metrics.xml, xap-extensions/xap-metrics-influxdb/src/main/java/com/gigaspaces/metrics/influxdb/InfluxDBHttpDispatcher.java, xap-extensions/xap-metrics-influxdb/src/main/java/com/gigaspaces/metrics/influxdb/InfluxDBReporter.java, xap-extensions/xap-metrics-influxdb/src/main/java/com/gigaspaces/metrics/influxdb/InfluxDBReporterFactory.java, xap-extensions/xap-metrics-influxdb/src/main/java/com/gigaspaces/metrics/influxdb/v_08/InfluxDBHttpDispatcher.java, xap-extensions/xap-metrics-influxdb/src/main/java/com/gigaspaces/metrics/influxdb/v_08/InfluxDBReporter.java, xap-extensions/xap-metrics-influxdb/src/test/java/com/gigaspaces/metrics/influxdb/InfluxDBHttpDispatcherTest.java
=> GS-14624 : add ability to supported HTTPS

xap-core/xap-common/src/main/java/com/gigaspaces/logger/LogUtils.java
Change severity matching to loglevel
=> PRX-289 : Change severity mapping for CEF logging

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/zookeeper/ZNodePathFactory.java
remove consumer/status zk path
=> RND-101 Consumer JMH benchmark 

xap-extensions/xap-metrics-hsqldb/pom.xml, xap-extensions/xap-metrics-hsqldb/src/main/java/com/gigaspaces/metrics/hsqldb/HsqlDbReporter.java, xap-extensions/xap-metrics-hsqldb/src/test/java/com/gigaspaces/metrics/hsqldb/HsqlDbReporterTest.java
[PRX-195](https://gigaspaces.atlassian.net/browse/PRX-195)
OPs manager stopped working due to ConcurrentModificationException
16.2.0-m9-ci-49
https://xap-builder.gspaces.com:8443/#job/61dc4fce4cedfd000c4c4e24/ALL
https://xap-builder.gspaces.com:8443/#job/61dc5a6f4cedfd000c4c4f05/ALL
=> PRX-195 modify logic of hsqldb all metrics property usage

xap-core/xap-datagrid/src/main/java/com/j_spaces/jdbc/QueryHandler.java
Add logic to proceed with the batch insertion
Newman job successfully passed - https://xap-builder.gspaces.com:8443/#job/61fd3f9e4cedfd000cd4776a/ALL
=> PRX-206 INSERT support in v3

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/metadata/IServerTypeDesc.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/metadata/SpaceTypeManager.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/tiered_storage/InternalRDBMS.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/tiered_storage/InternalRDBMSManager.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/tiered_storage/TieredStorageConfig.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/tiered_storage/TieredStorageManager.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/tiered_storage/TieredStorageManagerImpl.java, xap-core/xap-datagrid/src/main/java/com/j_spaces/core/IJSpace.java, xap-core/xap-openspaces/src/main/java/org/openspaces/core/DefaultGigaSpaceTypeManager.java, xap-core/xap-openspaces/src/main/java/org/openspaces/core/GigaSpaceTypeManager.java
- deprecate dropClass API
- expose unregisterTypeDescriptor API
- implement unregister type for tiered-storage
- add tests for tiered-storage embedded/remote/partitioned
=> PIC-36 Tiered Storage unregister type (drop class/table)

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/SpaceEngine.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/SpaceImpl.java
=> PIC-226 unregister type for broadcast table

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/ZookeeperTopologyHandler.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/zookeeper/ZNodePathFactory.java
=> PIC-256-DI-Consumer-configuration-file-refactor change z node path

pom.xml, xap-examples/hola-mundo/pom.xml
spring v5.3.19
spring security v5.6.2
=> PIC-506 upgrade Spring to most recent released version

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/SpaceEngine.java
=> PIC-414 Apply checks for result.size.limit and result.size.limit.memory setting

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/SpaceEngine.java, xap-core/xap-datagrid/src/main/java/com/j_spaces/core/cache/CacheManager.java
=> Revert "Dev ester gs14837 update full recover flag after recovery"

xap-core/xap-datagrid/src/main/java/com/gigaspaces/dih/consumer/ConsumerInternalException.java
PIC-490 manual topic recreate implementation
* update default CR8 port to 2050
* update ConsumerConfigurationTest unit test to run upon build
* update defaultConfig.json
* add DataIntegrationDelegator in order to run a-sync requests
* enforce manual topic recreation by user
* remove cleanStart api
=> PIC-490 manual topic recreate implementation

xap-core/xap-datagrid/src/main/java/com/gigaspaces/dih/consumer/MessageParsingException.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/dih/consumer/MissingConverterException.java
log upon start/failed full sync indicator
stop consumer and log upon stopped indicator
=> PIC-495 support batch load indicator

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/SpaceEngine.java
deleted the null check for setting tiered storage state for entry
=> PIC-787 update tiered storage state in context

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/tiered_storage/TieredStorageManager.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/tiered_storage/TieredStorageTableConfig.java, xap-core/xap-openspaces/src/main/java/org/openspaces/core/config/xmlparser/TieredStorageDefinitionsParser.java, xap-core/xap-openspaces/src/main/resources/org/openspaces/core/config/openspaces-core.xsd
remove retention field and all ref
=> PIC-850 removed retention field from tiered storage table config

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/cluster/node/impl/backlog/AbstractSingleFileGroupBacklog.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/redolog/DBMemoryRedoLogFile.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/redolog/DBSwapRedoLogFile.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/redolog/DBSwapRedoLogFileConfig.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/redolog/FixedSizeSwapRedoLogFile.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/redolog/IRedoLogFile.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/redolog/MemoryRedoLogFile.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/redolog/storage/DBPacketSerializer.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/redolog/storage/IRedoLogFileStorage.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/redolog/storage/SqliteRedoLogFileStorage.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/redolog/storage/SqliteStorageLayer.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/lrmi/classloading/LRMIClassLoadersHolder.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/metrics/MetricGroup.java, xap-core/xap-datagrid/src/main/java/com/j_spaces/kernel/JSpaceUtilities.java
PIC-908 fix packet serialization and deserialization bug. 
create a new API for getting the lastKey from redolog for metrics
add debug logger to JSpaceUtilities
tests -
https://groot.gspaces.com:8443/#build/6304d1e04cedfd000b4f3f7b
=> PIC-908 Persistent Redo log regression

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/remoting/RemoteOperationFutureListener.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/remoting/routing/clustered/ClusterRemoteOperationRouter.java
log async execution exception from inside async result object
=> PIC-508 prevent NPE when async result is empty

xap-core/xap-datagrid/src/main/java/com/gigaspaces/annotation/pojo/SpaceTieredStorageCacheRule.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/metadata/SpaceTypeInfo.java
from SpaceTieredStorageTableConfig to SpaceTieredStorageCacheRule
=> PIC-1013 Refactor tiered-storage annotation

pom.xml, xap-core/xap-common/src/main/java/com/gigaspaces/internal/version/PlatformVersion.java, xap-core/xap-openspaces/pom.xml, xap-examples/hello-world/pom.xml, xap-examples/hola-mundo/pom.xml, xap-extensions/xap-blueprints/blueprints/client/templates/pom.xml, xap-extensions/xap-blueprints/blueprints/dih-consumer/templates/pipeline-consumer-{{project.consumer-name-lower-case}}/pom.xml, xap-extensions/xap-blueprints/blueprints/pu-stateful-xml/templates/pom.xml, xap-extensions/xap-blueprints/blueprints/pu-stateful/templates/pom.xml, xap-extensions/xap-blueprints/blueprints/pu-stateless-xml/templates/pom.xml, xap-extensions/xap-blueprints/blueprints/pu-stateless/templates/pom.xml, xap-extensions/xap-blueprints/blueprints/stateful-with-db/templates/pom.xml, xap-extensions/xap-blueprints/src/test/resources/blueprints/dih-project/work/data-integration/pipeline-consumer-foo/pom.xml, xap-extensions/xap-jetty/pom.xml
Reverted commits for xap part:
- 0059855e (#223)
- aa307e45 (#247)
=> Zeppelin notebook test fix

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/SpaceImpl.java, xap-core/xap-datagrid/src/main/java/com/j_spaces/core/JSpaceAttributes.java, xap-core/xap-datagrid/src/main/java/com/j_spaces/core/admin/SpaceConfig.java, xap-core/xap-datagrid/src/main/java/com/j_spaces/core/admin/SpaceRuntimeInfo.java, xap-core/xap-datagrid/src/main/java/com/j_spaces/core/cache/CacheManager.java
remove implementation from space config and space impl and move it to run time info structure.
=> PIC-939 Extract tiered-storage config from SpaceRuntimeInfo

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/io/AnnotatedObjectOutputStream.java, xap-core/xap-datagrid/src/main/java/com/j_spaces/kernel/SystemProperties.java, xap-core/xap-datagrid/src/main/java/com/sun/jini/reggie/EntryClassBase.java, xap-core/xap-datagrid/src/main/java/com/sun/jini/reggie/ServiceTypeBase.java
Based on PR https://github.com/xap/xap/pull/268
Regression passed successfully on suites: xap-core, service-grid, manager and WAN
https://groot:8443/#build/63270aa04cedfd000bcba951
=> PIC-1031 Support disabling codebase field

xap-core/xap-datagrid/src/main/java/com/j_spaces/kernel/SystemProperties.java, xap-core/xap-datagrid/src/main/java/com/sun/jini/mahalo/TxnManagerTransaction.java
see also GS-14825
Discussed with Yechiel
=> PIC-1022 entry not available right after failed commit

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/cluster/node/impl/config/ReplicationNodeConfig.java
matching PR in xap - https://github.com/xap/xap/pull/300
solved problem in previous pr - https://github.com/xap/xap/pull/289
jobs: manager - https://xap-builder.gspaces.com:8443/#job/63553e064cedfd000bc8b030/ALL
service grid - https://xap-builder.gspaces.com:8443/#job/635528c94cedfd000bc89ed3/ALL
xap-core - https://xap-builder.gspaces.com:8443/#job/635528c94cedfd000bc89ed2/ALL
=> PIC-1119 Unable to replicate to mirror due to wrong regex pattern syntax

xap-core/xap-datagrid/src/main/java/com/sun/jini/mahalo/TxnManagerImpl.java, xap-core/xap-datagrid/src/main/java/com/sun/jini/mahalo/TxnManagerTransaction.java
additional refactor to assist in future debugging
=> PIC-1022 transaction exception handling

README.md, xap-dist/.gitignore, xap-examples/hello-world/.gitignore, xap-examples/hola-mundo/.gitignore
To be able to build, Scala is needed. This requirement has been added to the README.
After the build Git reports a number of files that are not under source control. These files have been added to .gitignore files.
Note: The CLA is on its way.
=> Build documentation and Git ignore improvements

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/metadata/TypeDesc.java
=> GS-14898 npe in read due to null in posiontsForScanning

xap-core/xap-datagrid/src/main/java/com/gigaspaces/lrmi/nio/PAdapter.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/lrmi/nio/selector/handler/client/ClientConversationRunner.java
Each time a proxy is created one more thread is created and never shutsdown although the proxy is closed
=> PIC-1653 close LRMI-async-client-selector-thread to avoid OOM in the client side

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/client/spaceproxy/actioninfo/ReadTakeByIdsProxyActionInfo.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/client/spaceproxy/metadata/SpaceProxyTypeManager.java
We need to discuss handling IdQuery and IdsQuery where the ids sent are not of the correct type
=> PIC-1995 - fix IdQuery and IdsQuery for BigDecimal id

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/SpaceEngine.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/SpaceImpl.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/executors/SpaceGetMVCCEntryMetaDataExecutor.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/mvcc/MVCCSpaceEngineHandler.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/mvcc/MVCCUtils.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/space/responses/GetMVCCEntryMetaDataResponseInfo.java, xap-core/xap-datagrid/src/main/java/com/j_spaces/core/cache/CacheManager.java, xap-core/xap-datagrid/src/main/java/com/j_spaces/core/cache/mvcc/MVCCCacheManagerHandler.java, xap-core/xap-datagrid/src/main/java/com/j_spaces/core/server/processor/Processor.java
https://gigaspaces.atlassian.net/browse/PIC-2264
=> PIC-2264: pre-rollback of operation by id that was aborted

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/client/spaceproxy/actioninfo/ChangeProxyActionInfo.java, xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/client/spaceproxy/actions/SpaceProxyImplChangeAction.java
- add change with lease operation to MvccUpdateOperationWithLeaseValidationTest;
- block change with lease for mvcc;
=> PIC-2443: block update and change with lease operation

pom.xml
fixes security test failure in ops-ui-secured suite
https://xap-builder.gspaces.com:8443/#job/6489ceac4cedfd000ba0ca5d/ALL
=> PIC-2606 include bouncycastle in xap-common

xap-extensions/xap-blueprints/blueprints/stateful-with-db/templates/pom.xml, xap-extensions/xap-blueprints/blueprints/stateful-with-db/templates/{{project.artifactId}}-mirror/pom.xml, xap-extensions/xap-blueprints/blueprints/stateful-with-db/templates/{{project.artifactId}}-space/pom.xml, xap-extensions/xap-blueprints/blueprints/stateful-with-db/values.yaml
- add hsqldb.version pom.xml for stateful-with-db blueprint;
=> PIC-2699: stateful with db blueprint fix

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/server/space/SpaceEngine.java
- handle empty shell error during update;
=> PIC-2449:  fix update error for mvcc;

xap-core/xap-datagrid/src/main/java/com/j_spaces/core/Constants.java
add MVCCCleanUp space properties
=> PIC-2848 MVCCCleanUp space properties

xap-core/xap-datagrid/src/main/java/com/gigaspaces/security/authorities/SpaceAuthority.java
FIX Newman test: add serial ID
=> FIX JarScannerTest :

pom.xml, xap-examples/hola-mundo/pom.xml
regression is clean https://xap-builder.gspaces.com:8443/#build/64cf4db44cedfd000bceb7d4
=> PIC-2952 upgrade Spring version to 5.3.29

xap-core/xap-datagrid/src/main/java/com/j_spaces/jdbc/driver/GConnection.java
Test for ensure new policy definition that contains spacename reference
=> PIC-2822 : first test of reading with certain permissions

xap-core/xap-datagrid/src/main/java/com/gigaspaces/security/authorities/PipelineAuthority.java
di-manager: https://github.com/giga-di/di-manager/pull/160
xap-premium: https://github.com/Gigaspaces/xap-premium/pull/792
=> PIC-3113 - Pipeline Filter added

xap-core/xap-openspaces/src/main/java/org/openspaces/core/space/InternalSpaceFactory.java
add security filter just for openid security manager and just for NOT remote spaces
=> PIC-3304 : add security filter just for openid security manager and j

pom.xml
upgrade dependencies:
```
<oshi.version>6.4.6</oshi.version>
<jna.version>5.13.0</jna.version>
```
=> PIC-3358 upgrade OSHI and JNA to latest version

xap-core/xap-datagrid/src/main/java/com/gigaspaces/internal/cluster/node/impl/backlog/SynchronizingData.java
https://groot.gspaces.com:8443/#job/654ca9574cedfd000b8c8a47/SUCCESS
=> PIC-3369 - Fix NPE in junit tests
